### PR TITLE
Fix resume game

### LINKED ISSUE #37: Resume option not available
Whenever you start a new game, when no resume option is not available and then you go back to the previous screen, the resume option is not available.

resume_error

### PR DESCRIPTION
**Pull request by rish971**
Fixes #37

### CODE REVIEW

**Comment by rajatgoyal715** [comment]
After selecting New Game option, changing orientation also changes the game matrix. You can get the value of resumeGame from SharefPref directly without sending this in the game intent.

File: app/src/main/java/com/rajatgoyal/puzzle15/util/SharedPref.java [hunk 1]
```diff
@@ -12,10 +12,10 @@
 
     private static final String GAME_PREF = "GAME_PREF";
     private static final String PLAYED_GAMES = "PLAYED_GAMES";
-    private static final String GAME_MATRIX_SIZE = "GAME_MATRIX_SIZE";
     private static final String GAME_MATRIX = "GAME_MATRIX";
     private static final String GAME_MOVES = "GAME_MOVES";
     private static final String GAME_TIME = "GAME_TIME";
+    private static final String RESUME_GAME = "RESUME_GAME";
```
Comment (rajatgoyal715) [inline app/src/main/java/com/rajatgoyal/puzzle15/util/SharedPref.java]: Please rename this flag to `RESUME_FLAG`
